### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by dcevid** [lorismichel/drf#12]
It seems there is a error if Y given is not a matrix but a vector.

This returns an error "Error in apply(object$Y.orig, 1, function(yy) transformation(yy)) : dim(X) must have a positive length"

fit <- drf(X = X, Y = Y[,2], num.trees=3000)
predict(fit, newdata=X_test, functional='quantile', quantiles=c(0.9))$quantile[,1,]

And it works if you put Y[,2,drop=FALSE]

**Comment by lorismichel** [comment]
Indeed, the response Y should be a matrix, this prevents unexpected behaviour with matrices and vector in R. That's why I feel it is good to keep it like that and not allow for vector input for Y in the one dimensional case.
